name: mary

services:
    app:
        build:
            context: ..
            dockerfile: .docker/Dockerfile
            target: base
        volumes:
            - ../:/var/www/html:cached
        ports:
            - "8018:8080"
            - "5174:5174"
